# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 469ae667e98ac64c1642fed4e798a23ec9a5cd022fb79adab107f4515747064f73955a42e3e52dde287d4c0a73c999804c6512e468d80653762b1dec46960136

test:
  secret_key_base: 35859d363f94f682372c61a25507908d8227993fa599f00a319653da3fcaa9ddf5449102af2ec90dd9ddf60b81ec67b4bda36ad99bdfb2f987966cb3c693811b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
